<?php

/**
 * @file
 * Handle Feedback types
 */

/**
 * Implements hook_help().
 */
function asu_feedback_help($path, $arg) {
  switch ($path) {
    case 'admin/help#asu_feedback':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The ASU Feedback module allows.....') . '</p>';
      return $output;

    case 'admin/config//asu_feedback':
      $output = '<p>' . t('ASU Feedback Moulde description goes here. Learn more on the <a href="@asufeedbackhelp">ASU Feedback module help page</a>.', array('@asufeedbackhelp' => url('admin/help/asu_feedback'))) . '</p>';
      return $output;
  }
}


/**
 * Implements hook_menu().
 */
function asu_feedback_menu() {
  return array(
    'admin/settings/asu_feedback' => array(
      'title' => 'ASU Feedback',
      'description' => 'Configure visibility of feedback options',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('asu_feedback_admin_settings'),
      'access arguments' => array('administer feedback types'),
     'file' => 'asu_feedback.admin.inc',
    ),
  );
}


/**
 * Implements hook_permission().
 */
function asu_feedback_permission() {
  $perms['administer feedback types'] = array(
    'title' => t('Administer feedback types'),
    'restrict access' => TRUE,
  );
  $perms['give feedback'] = array(
    'title' => t('Give feedback'),
    'restrict access' => TRUE,
  );
  return $perms;
}


/**
 * Implements hook_init().
 */
function asu_feedback_init() {
    $path = drupal_get_path('module', 'asu_feedback');
    drupal_add_css($path . '/asu_feedback.css');
    drupal_add_js($path . '/asu_feedback.js');
    drupal_add_js($path . '/cluetip/jquery.cluetip.js');
    //drupal_add_css($path . '/jquery.cluetip.css');
}

/**
 * Implements hook_page_build().
 */
function asu_feedback_page_build(&$page) {
  // test with hardcoded values
  $buttons = array();
  $buttons['feedback']['fid'] = 1;
  $buttons['feedback']['title'] = 'Leave Feedback';
  $buttons['feedback']['url'] = 'feedback';
  $buttons['feedback']['visibility'] = 0; // 0 = exclude paths
  $buttons['feedback']['paths'] = variable_get('asu_feedback_paths', '');
  $buttons['access']['fid'] = 2;
  $buttons['access']['title'] = 'Request Access';
  $buttons['access']['url'] = 'request-access';
  $buttons['access']['visibility'] =1; // 1 = include paths
  $buttons['access']['paths'] = variable_get('asu_feedback_access', '');
  $markup = '';
  foreach ($buttons as $button) {
      if (!asu_feedback_match_path($button['paths'])) {
        global $base_url;
        $url = '<li class="asu-feedback-' . $button['fid'] . '"><a target="_blank" href="' . $base_url;
        if (!user_is_logged_in()) {
          $url .= '/cas?destination=';
        }
        else {
          $url .= '/';
        } 
        $url .= $button['url'] . '?refer='. $base_url . '/' .  urlencode(drupal_get_path_alias($_GET['q'])) . '">' . $button['title'] .  '</a></li>';
 
        $markup .= $url;
     }
   }
        $markup = '<ul class="asu-feedback">' . $markup . '</ul>';
        $page['content']['asu_feedback'] = array(
          '#title' => t('Feedback'),
	  '#markup' => '<div id="feedback"><span class="asu-feedback-cluetip" rel="#feedback-tooltip"></span></div><div id="feedback-tooltip">' . $markup .'</div>',
        );
      
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * Adds link field to related Help article to the node form.
 *
 * @see asu_feedback_node_submit()
 */
function asu_feedback_form_node_form_alter(&$form, $form_state) {
  //$link = $form['#node']->menu;
  //$type = $form['#node']->type;
/*
  $form['help'] = array(
    '#type' => 'fieldset',
    '#title' => t('Menu settings'),
    '#access' => user_access('administer menu'),
    '#collapsible' => TRUE,
    '#collapsed' => !$link['link_title'],
    '#group' => 'additional_settings',
    '#attached' => array(
      'js' => array(drupal_get_path('module', 'menu') . '/menu.js'),
    ),
    '#tree' => TRUE,
    '#weight' => -2,
    '#attributes' => array('class' => array('menu-link-form')),
  );
 */
  $form['help']['enabled'] = array(
    '#type' => 'checkbox',
    '#title' => t('Provide a menu link'),
    '#default_value' => (int) (bool) $link['mlid'],
  );
  /*
  $form['menu']['link'] = array(
    '#type' => 'container',
    '#parents' => array('menu'),
    '#states' => array(
      'invisible' => array(
        'input[name="menu[enabled]"]' => array('checked' => FALSE),
      ),
    ),
  );
   */
  $form['help']['link'] = array(
      '#type' => 'textfield',
    '#title' => t('Help link'),
    '#default_value' => $link['link_title'],
  );

}

/**
 * Check if the current path matches any pattern in a set of patterns.
 *
 * @param $patterns
 *   String containing a set of patterns separated by \n, \r or \r\n.
 *
 * @return
 *   Boolean value: TRUE if the current path or alias matches a pattern.
 */
function asu_feedback_match_path($patterns) {
  // Convert path to lowercase. This allows comparison of the same path
  // with different case. Ex: /Page, /page, /PAGE.
  $patterns = drupal_strtolower($patterns);

  // Convert the current path to lowercase.
  $path = drupal_strtolower(drupal_get_path_alias($_GET['q']));

  // Compare the lowercase internal and lowercase path alias (if any).
  $page_match = drupal_match_path($path, $patterns);
  if ($path != $_GET['q']) {
    $page_match = $page_match || drupal_match_path($_GET['q'], $patterns);
  }

  return $page_match;
}


